var express=require('express');
var app=express();
var port=1010;
app.get('/',function(req,res){
    res.send("Response generated by my express js server");
})
app.listen(port,function(){
    console.log("Server running on port: " + port);
});